IOS_STRINGS = {

# -- Foundation
"WAMFoundationOkKey" => "OK",
"WAMFoundationDismiss" => "Dismiss",
"WAMFoundationCallKey" => "Call",
"WAMFoundationSMSKey" => "SMS",
"WAMFoundationNextKey" => "Next",
"WAMFoundationContinueKey" => "Continue",
"WAMFoundationDoneKey" => "Done",
"WAMFoundationSendKey" => "Send",
"WAMFoundationCancelKey" => "Cancel",
"WAMFoundationCloseKey" => "Close",
"WAMFoundationBackKey" => "Back",
"WAMFoundationSaveKey" => "Save",
"WAMFoundationRefineReset" => "Reset",
"WAMFoundationFavourites" => "Favourites",
"WAMFoundationError" => "Error",
"WAMFoundationInformation" => "Information",
"WAMFoundationSettings" => "Settings",
"WAMFoundationCurrentLocation" => "Current Location",
"WAMFoundationLocationAlertMsg" => "Please Turn on LifeWorks Location Access In Your iPhone's Settings",
"WAMFoundationGenericTermsAndConditions" => "Terms & Conditions",
"WAMFoundationCannotSendEmail" => "This device cannot send emails",
"WAMFoundationGenericError" => "Oops, something went wrong!",
"WAMFoundationDiscard" => "Discard",
"WAMFoundationKeep" => "Keep",
"WAMFoundationConfirm" => "Confirm",
"WAMFoundationSkip" => "Skip",
"WAMFoundationReadMore" => "Read more",
"WAMFoundationReadLess" => "Read less",
"WAMFoundationNetworkErrorTitle" => "Ooops. Looks like we've encountered a network error",
"WAMFoundationNetworkErrorDetails" => "Please check your connection and try again",
"WAMFoundationEmptyScreenTitle" => "No results",
"WAMFoundationEmptyScreenDescription" => "Oops, nothing to display here! :(",
"WAMFoundationHelpCentreLink" => "https:#help.lifeworks.com/hc/en-gb/requests/new",
"WAMFoundationTryAgain" => "Try Again",
"WAMFoundationCompanyName" => "LifeWorks",
"WAMFoundationRetry" => "Retry",
"WAMFoundationLetsGo" => "Let's Go",
"WAMFoundationContactUs" => "Contact Us",

# WAMImageRetrieveInteractor
"WAMImageRetrieveInteractorActionSheetCamera" => "Take Photo",
"WAMImageRetrieveInteractorActionSheetGallery" => "Choose from Library",
"WAMImageRetrieveInteractorActionSheetRemove" => "Remove Photo",
"WAMImageRetrieveInteractorActionSheetEditSettings" => "Edit Settings",
"WAMImageRetrieveInteractorPhotoLibraryNotAvailableError" => "Photo Library not available",
"WAMImageRetrieveInteractorCameraNotAvailableError" => "Camera not available",
"WAMImageRetrieveInteractorPhotoLibraryRequestAccess" => "To upload a photo you must give LifeWorks permission to access your photo library in your device settings",
"WAMImageRetrieveInteractorCameraRequestAccess" => "To upload a photo you must give LifeWorks permission to access your camera in your device settings",

# 2 of 18
"WAGalleryViewerFooterViewCounter" => "%d of %d",

# -- Others
"WAMRequirementEmailInvalidError" => "Please enter a valid email address.",

# -- Quick Actions
"WAMQuickActionGiveRecognitionTitle" => "Give Recognition",
"WAMQuickActionCreatePostTitle" => "Create a post",
"WAMQuickActionSearchColleagueTitle" => "Search colleagues",

# -- User List
"WAMFeedUserListWelcomed" => "Welcomed by",
"WAMFeedUserListLiked" => "Liked by",
"WAMFeedUserListCongratulated" => "Congratulated by",
"WAMFeedUserListRecognised" => "Recognised by",
"WAMFeedUserListOriginallyRecognisedBy" => "Originally recognised by:",
"WAMFeedUserListRecognisedUsers" => "Recognised",

# -- Cinemas Walkthrough
"WAMCIHelpNavigationBarTitle" => "How does it work?",
"WAMCIHelpViewTitle1" => "Make a purchase",
"WAMCIHelpViewTitle2" => "Redeem your code",
"WAMCIHelpViewSubTitle1" => "Getting your discount is easy. All you need to do is buy a cinema code which we will then send to your email.",
"WAMCIHelpViewSubTitle2" => "Show your codes at the cinema when buying tickets. You can also redeem the codes online",
"WAMCIHelpViewTitle3" => "Enjoy!",
"WAMCIHelpViewSubTitle3" => "Just sit back, relax, and enjoy the latest blockbuster movies at discounted prices exclusive to you.",

# -- Cinemas
"WAMCILocationsTitle" => "Choose a cinema",
"WAMCIDeliveryEmailTitle" => "Enter the email address you would like your codes to be sent to",

# -- Cinemas Empty Screen
"WAMCILandingEmptyScreenTitle" => "Oops, something went wrong!",
"WAMCILandingEmptyScreenDescription" => "Please try again later.",

# Date Calculations module, expiration feature
"WAMDateCalculationsExpired"=>"Expired",
"WAMDateCalculationsExpiresInLessThanOneMinute"=>"Expires in less than a minute",
"WAMDateCalculationsExpiresInMinutesOrHours"=>"Expires in %@", # Expires in 5 minutes, Expires in 3 hours. "5 minutes" and "3 hours" are generated by the operating system.
"WAMDateCalculationsExpiresDate"=>"Expires %@", # Expires 01/01/2001

"WAMGeneralMoreCashbackTitle" => "Get even more cashback!",
"WAMGeneralMoreCashbackContent" => "Share this link with your friends and family and get their earned Cashback straight to your wallet!",

"WAMDirectionsTitle" => "Directions",
"WAMDirectionsDetail" => "Which app do you want to use?",

# -- WAMLoginViewController
"WAMLoginViewControllerTermsAndPrivacyFullText" => "By logging in, you are agreeing to the <br/><a href => \"termslink\">Terms of service</a>",
"WAMLoginViewControllerEnvironmentChangeableButton" => "%@ Environment. Tap to change",
"WAMLoginViewControllerYourWorkEmailAddress" => "Email address or Username",
"WAMLoginViewControllerPassword" => "Password",
"WAMLoginHelpCentreFullText" => "Having trouble logging in? Check out our <a href=>\"helplink\">Help Centre</a>",

# Landing
"WAMLMLandingTitle" => "Feel Loved",
"WAMLMLandingSubtitle" => "The ultimate engagement platform that all employees love",
"WALMLLandingSignUp" => "Sign up",
"WAMLMLandingLogin" => "Log in",

# Login
"WAMLMInvalidMailFormat" => "Please enter a valid email address.",
"WAMLMLoginButton" => "Log In",
"WAMLMLoginIncorrectPassword" => "Incorrect password, please re-enter.",
"WAMLMLoginLegacyAccountTitle" => "Unable to access the iOS App",
"WAMLMLoginLegacyAccountMessage" => "Unfortunately your company needs to upgrade to access our iOS application but don't worry you can still enjoy LifeWorks here.",
"WAMLMLoginLegacyAccountOk" => "Access LifeWorks website",

# Company info
"WAMLMLoginCompanyInfoText" => "You will now be redirected to the %@ website to complete your login.",

# Recover password
"WAMLMLoginRecoverPassword" => "Forgotten your Password?",
"WAMLMLoginRecoverPasswordAlertTitle" => "Forgotten Password",
"WAMLMLoginRecoverPasswordAlertMsg" => "To reset your password, please enter your registered email address",
"WAMLMLoginRecoverPasswordAlertPlaceHolder" => "Email address",

# Recover password OK
"WAMLMLoginRecoverPasswordCompletedAlertTitle" => "Reset Password",
"WAMLMLoginRecoverPasswordCompletedAlertMsg" => "An email has been sent with a reset link. Please check your email to continue with the reset.",

# Recover password fail
"WAMLMLoginRecoverPasswordFailAlertTitle" => "Invalid email address",
"WAMLMLoginRecoverPasswordFailAlertMsg" => "The email address you have provided is invalid, please check your spelling.",

# -- Sign Up - User Information
"WAMSignupAddPhoto" => "Add Photo",
"WAMSignupFirstName" => "First Name",
"WAMSignupLastName" => "Last Name",
"WAMSignupJobTitle" => "Job Title",
"WAMSignupWorkEmail" => "Work e-mail address",
"WAMSignupPassword" => "Password",

"WAMSignupFirstNameError" => "Enter your first name",
"WAMSignupLastNameError" => "Enter your last name",
"WAMSignupJobTitleError" => "Enter your job title",
"WAMSignupWorkEmailError" => "Enter your email",
"WAMSignupPasswordRequirementsTitle" => "Your password needs to include:",
"WAMSignupPasswordError" => "A valid password",

# -- Internet Connection popup
"NoInternetAlertTitle" => "No internet connection",
"NoInternetAlertMsg" => "Please try again.",

# -- Network Deactivated
"WAMLoginSingUpErrorViewControllerNetworkDeatcivatedTitleText" => "Your network has been deactivated",
"WAMLoginSingUpErrorViewControllerNetworkDeatcivatedSubTitleText" => "Your data and content is still safe and secure. Please contact your administrator for more information.",
"WAMNetworkDeactivatedViewControllerEmailAdministratorButtonText" => "Email administrator",

# -- Account Deactivated
"WAMLoginSingUpErrorViewControllerAccountDeactivatedTitleText" => "Your account has been deactivated",

# -- Network Unavailable
"WAMLoginSingUpErrorViewControllerNetworkUnavailableTitleText" => "Your network is unavailable",
"WAMLoginSingUpErrorViewControllerNetworkUnavailableSubTitleText" => "LifeWorks is experiencing some technical difficulties. However we're working on fixing the issue. Please try again later.",

# -- Max failed attempts
"WAMLMLoginMaxFailedAttemptsAlertTitle" => "Account locked",
"WAMLMLoginMaxFailedAttemptsAlertMsg" => "You have exceeded the maximum number of login attempts, please try again in 10 minutes.",

# -- Waiting for Approval
"WAMLoginSingUpErrorViewControllerApprovalPendingTitleText" => "Approval Pending",

# -- Walkthrough
"WAMAppIntroEverydayWellnessTitle" => "Everyday Wellness",
"WAMAppIntroEverydayWellnessSubtitle" => "Boost your wellbeing and potential with best in class counselling, coaching and digital resources.",
"WAMAppIntroWellbeingOnboardingTitle" => "Everyday Wellbeing",
"WAMAppIntroWellbeingOnboardingSubtitle" => "Use snackable wellbeing to make a happier and healthier you",
"WAMAppIntroWellbeingOnboardingLetsBeginTitle" => "Before we Start",
"WAMAppIntroWellbeingOnboardingLetsBeginSubtitle" => "Tell us what you’d like to focus on so we\ncan recommend you the right wellbeing content.",
"WAMAppIntroExclusivePerksTitle" => "Exclusive Perks",
"WAMAppIntroExclusivePerksSubtitle" => "Get paid to shop. Save %@s a year with best in market cashback & discounts.",
"WAMAppIntroExclusivePerksSubtitleDefault" => "Get paid to shop. Save thousands a year with best in market cashback & discounts.",
"WAMAppIntroCompanyNewsFeedTitle" => "Company News Feed",
"WAMAppIntroCompanyNewsFeedSubtitle" => "Keep up to date with what's going on in your company.",
"WAMAppIntroGiveRecognitionTitle" => "Give Recognition",
"WAMAppIntroGiveRecognitionSubtitle" => "Recognise your colleagues for their hard work & achievements.",
"WAMAppIntroColleagueDirectoryTitle" => "Colleague Directory",
"WAMAppIntroColleagueDirectorySubtitle" => "Easily find all your colleagues and their contact details in your company colleague directory.",
"WAMAppIntroLetsGoButtonTitle" => "Get Started",
"WAMAppIntroBeginButtonTitle" => "Let's Begin",
"WAMAppIntroSkipButtonTitle" => "Skip for now",

# -- ColleagueDirectory
"WAMColleagueDirectoryViewControllerTitle" => "Colleague Directory",
"WAMColleagueDirectoryEmployees" => "%d Colleagues",
"WAMColleagueDirectoryActionSheetVoiceCallTitle" => "Voice Call",
"WAMColleagueDirectoryActionSheetSMSTitle" => "SMS",
"WAMColleagueDirectorySearchBarPlaceHolder" => "Search within your company",
"WAMColleagueDirectorySameCompanyGroup" => "In your group",
"WAMColleagueDirectorySearchNoResults" => "Oops, no results",
"WAMColleagueDirectorySearchNoResultsDetail" => "Please try again",

# -- Leaderboard
"WAMLeaderboardViewControllerTitle" => "Leaderboard",
"WAMLeaderboardViewControllerThisMonth" => "This Month",
"WAMLeaderboardViewControllerLastMonth" => "Last Month",
"WAMLeaderboardViewControllerAllTime" => "All Time",

# -- Child Leaderboard
"WAMLeaderboardChildViewControllerDeactivatedUserMessage" => "This user has been deactivated and cannot be recognised",

# -- Leaderboard EmptyView
"WAMLeaderboardEmptyViewMainMsg" => "Nobody has been recognised yet!",
"WAMLeaderboardEmptyViewBottomMsg" => "Be the first to recognise a colleague for their work now.",

# -- Leaderboard Header View
"WAMLeaderboardHeaderThisMonthLastDay" => "Last day this month to get recognised!",
"WAMLeaderboardHeaderLastMonth" => "Congratulations to last month's top performers!",
"WAMLeaderboardHeaderAllTime" => "Congratulations to the %@ top performers!",

# -- Individual recognitions
"WAMIndividualRecognitionsTitle" => "Recognition",
"WAMIndividualRecognitionsEmptyTitle" => "No recognition yet?",
"WAMIndividualRecognitionsEmptyDetail" => "Do something awesome in your team,\nand be recognised!",
"WAMColleagueIndividualRecognitionsEmptyTitle" => "No recognition yet?",
"WAMColleagueIndividualRecognitionsEmptyDetail" => "Recognise your colleague for their great work!",
"WAMColleagueIndividualRecognitionsMore" => "MORE",

# -- Validation View Controller
"WAMValidationJoinButtonTitle" => "Join",
"WAMValidationTextFieldPlaceholder" => "Invitation Code",
"WAMValidationQuestionAlertTitle" => "Invitation Code",
"WAMLMValidationInfoButton" => "Where is my invitation code?",
"WAMValidationQuestionAlertContent" => "Your invitation code appears in your invitation email and is\n usually 12 characters with a combination of letters and numbers.",
"WAMValidationErrorAlertContent" => "Please enter a valid invitation code.",

# -- Signup ViewController
"WAMSignupViewControllerTitle" => "Sign up",
"WAMSignupErrorAlertViewContent" => "Oops! Something’s gone wrong.",
"WAMSignupErrorAlertViewButton" => "Try again",
"WAMSignupErrorAlertViewRepeatedUserTitle" => "Email Already Exists",
"WAMSignupErrorAlertViewRepeatedUserContent" => "The email address you've entered has already been registered. Please log in with your existing credentials.",
"WAMSingupErrorAlertViewRepeatedUserButton" => "Login",

"WAMSignUpHelpCentreFullText" => "Having trouble signing up? Check out our <a href=>\"helplink\">Help Centre</a>",

# -- Shop Online Categories
"WAMShopOnlineCategoryAll" => "All",
"WAMShopOnlineCategoryFashion" => "Fashion",
"WAMShopOnlineCategoryElectronics" => "Electronics",
"WAMShopOnlineCategoryFood" => "Food & Beverage",
"WAMShopOnlineCategoryGift" => "Gifts & Gift Cards",
"WAMShopOnlineCategoryHealth" => "Health & Beauty",
"WAMShopOnlineCategoryHome" => "Home & Garden",
"WAMShopOnlineCategoryInsurance" => "Insurance",
"WAMShopOnlineCategoryMedia" => "Media",
"WAMShopOnlineCategorySports" => "Sports",
"WAMShopOnlineCategoryTravel" => "Travel",
"WAMShopOnlineCategoryTickets" => "Tickets",
"WAMShopOnlineCategoryUtilities" => "Utilities",
"WAMShopOnlineCategorySaveOffers" => "Saved Offers",

# -- Shop Online View Controller
"WAMShopOnlineViewControllerTitle" => "Shop Online",
"WAMShopOnlineBrowseCategoryText" => "Browse by Category",
"WAMShopOnlineBrowseCategoryTitle" => "Browse by Category",
"WAMShopOnlineLandingSeeAll" => "See All",
"WAMShopOnlineLandingComponentError" => "Oops something went wrong. Refresh or check back again later.",
"WAMShopOnlineRecommendedOffersNoInterestTitle" => "Looks like you have not set up your interests yet!",
"WAMShopOnlineRecommendedOffersNoInterestDetail" => "Tell us what your're interested in and get personalised recommendations.",
"WAMShopOnlineRecommendedOffersNoMatchTitle" => "No match found",
"WAMShopOnlineRecommendedOffersNoMatchDetail" => "We cannot find a match between the interests that you set and the deals. Do you want to change your interests?",
"WAMShopOnlineRecommendedOffersSelectInterests" => "Select Interests",

"WAMShopOnlineBrowseRetailersTitle" => "Browse Retailers",
"WAMShopOnlineBrowseRetailersSort" => "Sort",

"WAMShopOnlineNoFavouritesLabelTitle" => "No Favourites!",
"WAMShopOnlineNoFavouritesLabelDescription" => "You haven't saved any retailers yet, why don't you check out some of our favourites below?",
"WAMShopOnlineNoSavedOffersEmptyTitle" => "No Saved Offers!",
"WAMShopOnlineNoSavedOffersEmptyDescription" => "You haven't saved any offers yet, why don't you check out some of our special offers below?",
"WAMShopOnlineBrowseRetailersSortHighestCashback" => "Highest Cashback",
"WAMShopOnlineBrowseRetailersSortByRetailersAZ" => "Alphabetical (Retailer)",
"WAMShopOnlineBrowseRetailersSortByEnding" => "Ending Soon",

# -- Shop Online - Boosted Cashback Popup

"WAMShopOnlineBoostedCashbackSubtitle" => "Your company is giving you exclusive <b>BOOSTED Cashback</b> rates on all your online shopping*.",
"WAMShopOnlineBoostedCashbackDetail" => "*The Boosted Cashback rate is only applicable on your first %@ overall spend per month on the LifeWorks platform. Always read the retailer's Terms and Conditions. For more information check out our Help & FAQ pages.",

# -- Shop Online - Benefit Terms & Conditions
"WAMTermsAndConditionsNoTermsTitle" => "Nothing to see here",
"WAMTermsAndConditionsNoTermsDescription" => "%@ doesn't have any additional terms and conditions.",

# -- Shop Online - All Special Offers
"WAMShopOnlineAllSpecialOffersTitle" => "All Special Offers",

# -- Shop Online - Cashback Template
"WAMCashbackTemplatePercentage" => "%@",
"WAMCashbackTemplateFixAmount" => "%@",
"WAMCashbackTemplateUptoPercentage" => "Up to %@",
"WAMCashbackTemplateUptoFixAmount" => "up to %@",
"WAMCashbackWordTemplate" => "Cashback",
"WAMCashbackGuaranteed" => "%@ cashback guaranteed",
"WAMCashbackWas" => "was",
"WAMCashbackBoostedTemplate" => "%@ boosted cashback",

# -- Shop Online - Retailer
"WAMShopOnlineRetailerDetails" => "Retailer Details",
"WAMShopOnlineRetailerSpecialOffers" => "Special Offers",
"WAMShopOnlineRetailerSpecialOffersSeeAll" => "See All",
"WAMShopOnlineRetailerTermsAndConditions" => "Terms & Conditions",
"WAMShopOnlineRetailerShopNow" => "Shop Now",
"WAMShopOnlineRetailerCashBackAllProducts" => "On all Retailer's products",
"WAMShopOnlineRetailerSavedButton" => "Saved",

"WAMShopOnlineRetailerCashbackTerms" => "See %@",
"WAMShopOnlineRetailerCashbackTermsAction" => "terms & conditions",

# -- Shop Online - Retailer Email Sharing
"WAMShopOnlineRetailerEmailSubject" => "Your LifeWorks cashback link",
"WAMShopOnlineRetailerEmailBody" => "Hi\nHere’s your requested cashback tracking link for %1$@.\nLink: Cashback Tracking Link %2$@\nUse this link on your\ndesktop or share it with friends and family to receive your cashback.\nHappy shopping!\n\nThanks,\nLifeWorks Team",

# -- Shop Online - Compare Retailers
"WAMShopOnlineCompareRetailersTitle" => "Compare retailers",
"WAMShopOnlineCompareRetailersFromLabel" => "from %@",
"WAMShopOnlineCompareRetailersListTitle" => "Retailers",

# -- Shop Online - Search
"WAMShopOnlineSearchPlaceholder" => "Search retailers or products",
"WAMShopOnlineSearchRetailersSegmentTitle" => "Retailers",
"WAMShopOnlineSearchProductsSegmentTitle" => "Products",
"WAMShopOnlineSearchNoResultsTitle" => "Oops, no result!",
"WAMShopOnlineSearchNoResultsDescription" => "We couldn't find any result matching \"%@\", try searching for something else or check out some of our offers below?",
"WAMShopOnlineSearchRetailerRecentTile" => "Recent searches",
"WAMShopOnlineSearchClearHistoryLabel" => "Clear",

# -- Shop Online - Products Search
"WAMShopOnlineProductSearchPriceFrom" => "from %@",
"WAMShopOnlineProductSearchPriceUpTo" => "up to %@ Cashback",

# --- Shop Online - Cashback rates
"WAMShopOnlineRetailerCashBackRatesTitle" => "Cashback rates",
"WAMShopOnlineRetailerCellDescriptionOption1" => "%@ on all Retailer's products",
"WAMShopOnlineRetailerCellDescriptionOption2" => "%1$@ on %2$@",
"WAMShopOnlineRetailerCellRatesAvailable" => "%d RATES AVAILABLE",

"WAMShopOnlineBoostedCashbackLearnMore" => "Learn more.",
"WAMShopOnlineBoostedCashbackText" => "Cashback rates are boosted on your first %@ overall spend each month.",

# -- Web app browser
"WAMAppBrowserLoadingFirstLine" => "Congratulations %@, you're on your way to %@",
"WAMAppBrowserLoadingSecondLine" => "Please complete your transaction on the\nwebsite before navigating away.",
"WAMAppBrowserRedemptionTitle" => "Code has been copied to your clipboard, paste at checkout",
"WAMAppBrowserCashbackAmount" => "%@ cashback",

# -- Shop Online - Featured Cashback
"WAMShopOnlineFeaturedCashbackTitle" => "Featured Cashback",
"WAMShopOnlineFeaturedCashbackCardTitle" => "Get Cashback on exclusive special offers!",
"WAMShopOnlineFeaturedCashbackCardDescription" => "The best special offers available, with Cashback on top to help you save even more.",

# -- Shop Online - Featured Offers
"WAMShopOnlineFeaturedOffersTitle" => "Featured Offers",
"WAMShopOnlineFeaturedOffersCardTitle" => "Get Cashback on exclusive special offers!",
"WAMShopOnlineFeaturedOffersCardDescription" => "The best special offers available, with Cashback on top to help you save even more.",

# -- Shop Online - Popular in Network
"WAMShopOnlinePopularInNetworkTitle" => "Popular in Network",
"WAMShopOnlinePopularInNetworkCardTitle" => "See what's popular amongst your colleagues!",
"WAMShopOnlinePopularInNetworkCardDescription" => "The most popular retailers and special offers in your company network.",

# -- Shop Online - Recommended Offers
"WAMShopOnlineRecommendedOffersTitle" => "Recommended Offers",
"WAMShopOnlineRecommendedOffersCardTitle" => "Tailored recommendations specially for you!",
"WAMShopOnlineRecommendedOffersCardDescription" => "We've selected some retailers and special offers that we think you'll love.",

# -- Shop Online - Empty Featured View
"WAMShopOnlineEmptyFeaturedViewSeeAll" => "See All",
"WAMShopOnlineEmptyFeaturedOffers" => "Featured Offers",

# -- Shop Online - Boosted Cashback Terms and Conditions
"WAMShopOnlineGenericTermsAndConditionsTitle" => "Boosted Cashback",
"WAMShopOnlineGenericTermsAndConditionsHeadlineTitle" => "Terms and Conditions",
"WAMShopOnlineGenericTermsAndConditionsHeadlineText" => "You receive an exclusive boosted cashback rate on your first %1$@ overall spend each month on the LifeWorks platform. Cashback is only boosted for percentage based rates and is excluded on fixed amount cashback rates",
"WAMShopOnlineGenericTermsAndConditionsText" => "If available, please check the 'Special Terms' of a retailer before visiting the retailer's website as certain products or services may have different cashback rates associated with them or may be excluded from cashback altogether. \n\nCashback will not be paid in conjunction with any other offer, voucher or discount code unless listed on this page, or with any other discounts such as staff or student discount. Cashback may not be paid on VAT, delivery, card payment fees, taxes or any other additional charges",

# -- Recognition Feed
"WAMRecognitionFeedTitle" => "News Feed",
"WAMFeedPostTitle" => "Post",
"WAMRecognitionSegmentFeedTitle" => "My Feed",
"WAMRecognitionSegmentGroupTitle" => "Groups",
"WAMRecognitionFeedButtonLike" => "Like",
"WAMRecognitionFeedButtonLiked" => "Liked",
"WAMRecognitionFeedButtonCongratulate" => "Congratulate",
"WAMRecognitionFeedButtonCongratulated" => "Congratulated",
"WAMRecognitionFeedButtonWelcome" => "Welcome",
"WAMRecognitionFeedButtonWelcomed" => "Welcomed",
"WAMRecognitionFeedButtonRe-Recognise" => "Re-Recognise",
"WAMRecognitionFeedButtonRe-Recognised" => "Recognised",
"WAMRecognitionFeedButtonZeroComment" => "Comment",
"WAMRecognitionFeedLikedBySingle" => "Liked by %@",
"WAMRecognitionFeedLikedByDouble" => "Liked by %1$@ and %2$@",
"WAMGroupSubscriptionButtonTitleNormal" => "Subscribe",
"WAMGroupSubscriptionButtonTitleSelected" => "Subscribed",
"WAMGroupSubscriptionButtonTitleSelectedBis" => "Unsubscribe",
"WAMGroupSubscriptionMyGroupTitle" => "My Group",
"WAMGroupUnsubscribeAlertMessage" => "Are you sure you want to unsubscribe from %@?",

"WAMRecognitionFeedFirstToLike" => "Be the first to Like",
"WAMRecognitionFeedFirstToCongratulate" => "Be the first to Congratulate",
"WAMRecognitionFeedFirstToWelcome" => "Be the first to Welcome",

"WAMRecognitionFeedUserAnniversaryCongratulation" => "Congratulations %@!",

"WAMRecognitionFeedCongratulatedBySingle" => "Congratulated by %@",
"WAMRecognitionFeedCongratulatedByDouble" => "Congratulated by %1$@ and %2$@",

"WAMRecognitionFeedWelcomedBySingle" => "Welcomed by %@",
"WAMRecognitionFeedWelcomedByDouble" => "Welcomed by %1$@ and %2$@",

"WAMRecognitionFeedRecognisedBySingle" => "Recognised by %@",
"WAMRecognitionFeedRecognisedByDouble" => "Recognised by %1$@ and %2$@",

"WAMRecognitionFeedHappyBirthdayMessage" => "Have a great day, from the whole %@ team. 🎂",
"WAMRecognitionFeedCompanyAnniversaryCelebrating" => "Today we're celebrating our %@ anniversary 🎂",
"WAMRecognitionFeedWelcomeMessageHim" => "%1$@ has joined %2$@, please give him a warm welcome 👋",
"WAMRecognitionFeedWelcomeMessageHer" => "%1$@ has joined %2$@, please give her a warm welcome 👋",
"WAMRecognitionFeedWelcomeMessageThem" => "%1$@ has joined %2$@, please give them a warm welcome 👋",
"WAMRecognitionFeedRecognitionGotRecognised" => "%@ has been recognised!",
"WAMRecognitionFeedRecognitionGotRecognisedDouble" => "%1$@ and %2$@ have been recognised!",
"WAMRecognitionFeedRecognitionGotRecognisedTriple" => "%1$@, %2$@ and %3$@ have been recognised!",
"WAMRecognitionFeedRecognitionGotRecognisedQuadruple" => "%1$@, %2$@, %3$@ and %4$@ have been recognised!",
"WAMRecognitionFeedRe-RecogniseAlreadyPostedAlertTitle" => "Re-Recognise",
"WAMRecognitionFeedRe-RecogniseAlreadyPostedAlertMessage" => "Your re-recognition has already been posted, but we like your enthusiasm!",

"WAMFeedTopPerformersTitle" => "Congratulations to last month’s top performers, great job! 🏆",
"WAMFeedUserAnniversaryBody" => "%1$@ years ago today, you joined %2$@",
"WAMFeedMilestoneBody" => "%1$@ has achieved the %2$@ milestone! Amazing work.",
"WAMFeedMilestoneTitle" => "Awesome %@!",
"WAMFeedNewJoinerTitle" => "Welcome aboard %@!",
"WAMFeedTwitterLink" => "View on Twitter",

# -- Feed Promoted Post
"WAMFeedMarkPostAsRead" => "Mark post as read",
"WAMFeedPostWontAppearAnymore" => "This post will no longer appear at the top of your newsfeed",
"WAMFeedPostHasBeenMarkedAsRead" => "Post has been marked as read",
"WAMFeedCompanyPostPromotedBy" => "Promoted by %@",

# -- Feed Filter
"WAMFeedFilterAll" => "All",
"WAMFeedFilterCompanyPosts" => "Company Posts",
"WAMFeedFilterRecognitions" => "Recognitions",
"WAMFeedFilterPosts" => "Posts",
"WAMFeedFilterTopPerformers" => "Top Performers",
"WAMFeedFilterBy" => "Filter by",
"WAMFeedFilterTitle" => "Refine News Feed",
"WAMFeedFilterRefineTitle" => "Refine",
"WAMFeedFilterEmptyViewTitleFilter" => "Oops, no \"%@\"",
"WAMFeedFilterEmptyViewTitleGeneric" => "Oops! It look like there aren’t any posts yet. Check back soon to see what’s happening.",
"WAMFeedFilterEmptyViewDetail" => "No results for \"%@\" yet. Try refining by a different type of post.",

# -- Recognize Colleagues
"WAMRecognizeColleaguesViewControllerTitle" => "Select Colleagues",
"WAMRecognizeColleaguesSearchNoResults" => "Uh oh,no results!",
"WAMRecognizeColleaguesSearchNoResultsDetail" => "Please try again",

"WAMSearchColleaguePlaceholder" => "Search colleague...",

# -- Give recognition
"WAMGiveRecognitionPostLabel" => "Post",
"WAMGiveRecognitionTitleLabel" => "Give Recognition",
"WAMLoadingProgressViewFailed" => "Failed",
"WAMGiveRecognitionSenderTemplateFor1" => "\U2014 %@.",
"WAMGiveRecognitionSenderTemplateFor2" => "\U2014 %1$@ and %2$@.",
"WAMGiveRecognitionPlaceHolderText" => "Write your recognition...",
"WAMGiveRecognitionRemoveToolTipIntroTitle" => "Tap to Remove",
"WAMGiveRecognitionRemoveToolTipIntroSubtitle" => "Tap the Faces\nto remove them.",
"WAMGiveRecognitionRemoveToolTip" => "Remove",
"WAMGiveRecognitionCloseAlertControllerMessage" => "If you cancel now, your recognition will be discarded",

# -- Select Badge
"WAMSelectBadgeTitle" => "Select a Badge",

# -- Recognition Feed FeedBarView
"WAMRecognitionFeedButtonBarGiveRecognitionTitle" => "Give Recognition",
"WAMRecognitionFeedButtonBarCreateNewPostTitle" => "Create New Post",

# -- Recogntion Feed Comments Screen
"WAMRecognitionFeedAddCommentPlaceHolderText" => "Add a comment...",

# -- Recogntion Feed Send Comment
"WAMRecogntionFeedSendCommentTitle" => "Comment",
"WAMRecogntionFeedSendCommentPostTitle" => "Post",
"WAMRecogntionFeedSendCommentPlaceHolderText" => "Write your comment...",

# -- Recogntion Feed Send Post
"WAMRecogntionFeedSendPostTitle" => "New Post",
"WAMRecogntionFeedSendPostPlaceHolderText" => "Write your post...\n\nUse the @ to mention a colleague",
"WAMRecogntionFeedSendPostCloseAlertControllerMessage" => "If you cancel now, your post will be discarded",
"WAMRecogntionFeedSendPostShareToMyGroup" => "%@ (My Group)",

# -- Recogntion Feed Search
"WAMRecognitionFeedSearchPlaceholder" => "Search posts",

# -- Group Search
"WAMGroupSubscriptionSearchPlaceholder" => "Search groups",

# -- Rewards
"WAMRewardsTitle" => "Rewards",
"WAMRewardAvailable" => "Available",
"WAMRewardAvailableCellTitle" => "You have been rewarded:",
"WAMRewardAvailableEmptyViewTitle" => "You don't have any available Rewards yet.",
"WAMRewardAvailableEmptyViewSubTitle" => "Your available Rewards will appear here.",
"WAMRewardRedeemed" => "Redeemed",
"WAMRewardRedeemedEmptyViewTitle" => "You haven't redeemed any Rewards yet.",
"WAMRewardRedeemedEmptyViewSubTitle" => "Your redeemed Rewards will appear here.",
"WAMRewardEmptyViewButtonTitle"  => "Find out how it works",
"WAMRewardDeliveryDetailsTitle" => "Your Delivery Details",
"WAMRewardDeliveryExplanation" => "Your chosen gift card will be delivered to this address. Once you confirm this selection, a confirmation email will be sent with your Reward details.",
"WAMRewardDeliveryInfoTitle" => "Delivery Information",
"WAMRewardDeliveryAddressLine1" => "Address Line 1",
"WAMRewardDeliveryAddressLine2" => "Address Line 2 (Optional)",
"WAMRewardDeliveryCity" => "City",
"WAMRewardDeliveryPostCode" => "Postcode",
"WAMRewardDispatchText" => "We currently only dispatch to the UK",
"WAMRewardSelectCountryTitle" => "Select a country",
"WAMRWProviderTerms" => "Provider Terms and Conditions",

# Reward Delivery Details Errors
"WAMRewardDeliveryRequiredFieldError" => "This is a required field",

"WAMRWDigitalCard" => "Digital Card",
"WAMRWPhysicalCard" => "Physical Card",
"WAMRWChooseReward" => "Choose This Reward",
"WAMRWDetailTitle" => "Gift Card Detail",
"WAMRWChooseRewardConfirmationTitle" => "Choose this reward?",
"WAMRWChooseRewardConfirmationDetail" => "Once you confirm the selection, a confirmation email will be sent with your reward details.",
"WAMRWChooseYourRewardTitle" => "Choose your %@ reward",

# -- Reward Cells
"WAMRWAvailableRewardCellSentDate" => "Sent: %@",
"WAMRWAvailableRewardCellRedeemedDate" => "Redeemed: %@",

# -- User Profile
"WAMColleagueProfileTitle" => "Colleague Profile",

"WAMUserProfileTitle" => "My Profile",
"WAMUserProfileEditProfileTitle" => "Edit Profile",
"WAMUserProfileHeaderJoined" => "Joined %@",

"WAMUserCoverTitle1" => "Work with passion!",
"WAMUserCoverTitle2" => "Present your work today!",
"WAMUserCoverTitle3" => "You’re a genius!",
"WAMUserCoverTitle4" => "Share your ideas today!",
"WAMUserCoverTitle5" => "Lend a helping hand today!",
"WAMUserCoverTitle6" => "Go the extra mile today!",
"WAMUserCoverTitle7" => "Your energy is awesome today!",
"WAMUserCoverTitle8" => "You can make that deadline!",
"WAMUserCoverTitle9" => "You can achieve so much today!",
"WAMUserCoverTitle10" => "Have an open mind today!",

"WAMColleagueCoverTitle1" => "Do you think I’m\na passionate worker?",
"WAMColleagueCoverTitle2" => "Do you think I’m\na great presenter?",
"WAMColleagueCoverTitle3" => "Do you think I’m\na little genius?",
"WAMColleagueCoverTitle4" => "Do you think I have\ngreat ideas?",
"WAMColleagueCoverTitle5" => "Do you think I’m\na helpful colleague?",
"WAMColleagueCoverTitle6" => "Do you think I go\nthe extra mile?",
"WAMColleagueCoverTitle7" => "Do you think\nI’m energetic?",
"WAMColleagueCoverTitle8" => "Do you think I’m good\nat time management?",
"WAMColleagueCoverTitle9" => "Do you think I’m\na high achiever?",
"WAMColleagueCoverTitle10" => "Do you think I’m\nopen minded?",

# -- User Profile - CellTypes
"WAMUserProfileCellTypeGroup" => "Group",
"WAMUserProfileCellTypeName" => "Name",
"WAMUserProfileCellTypeSurname" => "Surname",
"WAMUserProfileCellTypeJobTitle" => "Job Title",
"WAMUserProfileCellTypeJoined" => "Joined %@",
"WAMUserProfileCellTypeEmail" => "Email",
"WAMUserProfileCellTypeWork" => "Work",
"WAMUserProfileCellTypeGender" => "Gender",
"WAMUserProfileCellTypeMobile" => "Mobile",
"WAMUserProfileCellTypeBirthday" => "Birthday",
"WAMUserProfileCellTypeBirthdaySetting" => "Display my year of birth",

# -- User Profile - Achievements
"WAMUserProfileAchievementsTitle" => "Achievements",
"WAMUserProfileMyAchievementsTitle" => "My Achievements",
"WAMUserProfileAchievementsBadgeTitle" => "Badges",
"WAMUserProfileAchievementsMilestoneTitle" => "Milestones",
"WAMUserProfileAchievementsMedalsTitle" => "Medals",

# -- User Profile - Achievements - Milestones
"WAMMilestoneNumRecognitions" => "%@ Recognitions",
"WAMMilestonePendingInformation" => "Be recognised %@ times by your colleagues to reach this milestone!",
"WAMMilestoneAllCollectedTitle" => "All Milestones collected!",
"WAMMilestoneAllCollectedDetail" => "Stay tuned, more Milestones are coming soon!",

"WAMMilestoneNewbieTitle" => "Newbie",
"WAMMilestoneNewbieInformation" => "Welcome Newbie! Well done for your first Milestone. Keep going!",
"WAMMilestoneHotshotTitle" => "Hotshot",
"WAMMilestoneHotshotInformation" => "Your amazing work ethic is being recognised. Continue impressing!",
"WAMMilestoneRockstarTitle" => "Rockstar",
"WAMMilestoneRockstarInformation" => "Awesome! You make recognitions look easy. Keep pleasing those fans!",
"WAMMilestoneMasterTitle" => "Master",
"WAMMilestoneMasterInformation" => "Its official, you’re the master of Milestones. Calculate your way up!",
"WAMMilestoneChampionTitle" => "Champion",
"WAMMilestoneChampionInformation" => "You are a champion of recognition, long may your success continue!",
"WAMMilestoneLegendTitle" => "Legend",
"WAMMilestoneLegendInformation" => "Your work is legendary, tales of your success will be told forever!",

# -- User Profile - Achievements - Medals
"WAMMedalsGoldTitle" => "Gold",
"WAMMedalsSilverTitle" => "Silver",
"WAMMedalsBronzeTitle" => "Bronze",
"WAMMedalsAchievedGold" => "You achieved a gold medal in:",
"WAMMedalsAchievedSilver" => "You achieved a silver medal in:",
"WAMMedalsAchievedBronze" => "You achieved a bronze medal in:",
"WAMMedalsEmptyTitle" => "No medals yet?",
"WAMMedalsEmptyDetail" => "Earn a medal in the blink of an eye.\nJust do something amazing!",
"WAMColleagueMedalsEmptyTitle" => "No medals yet?",
"WAMColleagueMedalsEmptyDetail" => "Recognise your colleague to help them earn a medal!",

# -- User Profile - Timeline - Progression
"WAMMyAverageProgression" => "MY AVERAGE\n RECOGNITIONS",
"WAMColleagueAverageProgression" => "AVERAGE\n RECOGNITIONS",
"WAMTimelineJoined" => "JOINED",
"WAMTimelineProgression" => "%@'s Progression",

# -- User Profile - Edit Profile
"WAMUserProfileCounterTextViewPlaceholder" => "Write something awesome about yourself and your job!",
"WAMEditUserProfileTitle" => "Edit Profile",
"WAMEditUserProfileSaveProfileButtonTitle" => "Save Profile",
"WAMEditUserProfileInvalidJoinedDateAlertTitle" => "Invalid date",
"WAMEditUserProfileInvalidJoinedDateAlertMsg" => "Your joined date cannot be before the date the company was created",

"WAMSelectGenderMale" => "Male",
"WAMSelectGenderFemale" => "Female",
"WAMSelectGenderUnkown" => "Other",

# -- User Profile - Interests
"WAMUserProfileInterestsTitle" => "Interests",
"WAMUserProfileSelectInterestsTitle" => "Select your Interests",
# -- Sign Up - Interests */
"WAMInterestsViewControllerSportsAndOutdoor" => "Sports",
"WAMInterestsViewControllerHealthAndWellbeing" => "Health",
"WAMInterestsViewControllerArtAndPhotography" => "The arts",
"WAMInterestsViewControllerFilmTvAndBooks" => "Media",
"WAMInterestsViewControllerMusic" => "Music",
"WAMInterestsViewControllerWomen" => "Female Fashion",
"WAMInterestsViewControllerFoodAndDrinks" => "Food & Drinks",
"WAMInterestsViewControllerHairAndBeauty" => "Hair & Beauty",
"WAMInterestsViewControllerMens" => "Male Fashion",
"WAMInterestsViewControllerToysAndGames" => "Toys",
"WAMInterestsViewControllerCars" => "Cars",
"WAMInterestsViewControllerTravelling" => "Travel",
"WAMInterestsViewControllerTechnology" => "Tech",
"WAMInterestsViewControllerTicketsAndEvents" => "Events",
"WAMInterestsViewControllerHomeAndGarden" => "Home & Garden",

# -- User Profile - Profile Settings
"WAMUserProfileSettingsSectionWellbeing" => "WELLBEING",
"WAMSettingsTypeWellbeingInterests" => "Snackable Topics",

# -- User Profile - Profile Settings */
"WAMUserProfileSettingsSectionSupport" => "SUPPORT",

"WAMSettingsTypePackage" => "Package",
"WAMSettingsTypeNotifications" => "Notifications",
"WAMSettingsTypePushNotifications" => "Push Notifications",
"WAMSettingsTypeEmailNotifications" => "Email Notifications",
"WAMSettingsTypeAppIntro" => "App Intro",
"WAMSettingsTypeContactLifeWorks" => "Contact LifeWorks",
"WAMSettingsTypeFAQs" => "FAQs",
"WAMSettingsTypeAbout" => "About",
"WAMSettingsTypeTermsAndConditions" => "Terms & Conditions",
"WAMSettingsTypePrivacyPolicy" => "Privacy Policy",
"WAMSettingsTypeLogOut" => "Log out",

"WAMUserProfileSettingsLogOutTitle" => "Log out?",
"WAMUserProfileSettingsLogOutAlertViewMessage" => "Are you sure you want to log out?",

# -- User Profile - Settings - Notifications
"WAMSettingsNotificationSection1" => "Savings",
"WAMSettingsNotificationSection2" => "Cashback",
"WAMSettingsNotificationSection3" => "Recognition",
"WAMSettingsNotificationSection4" => "Posts & Comments",
"WAMSettingsNotificationSection5" => "Grouping",
"WAMSettingsNotificationSavingsNews" => "Savings news",
"WAMSettingsNotificationSavingsNewSpecialOffers" => "New special offers",
"WAMSettingsNotificationCashbackTrack" => "Cashback tracking confirmation",
"WAMSettingsNotificationCashbackWithdraw" => "Cashback available to withdraw",
"WAMSettingsNotificationCashbackWithdrawReceived" => "Cashback withdrawal has been received",
"WAMSettingsNotificationsCashbackWithdrawConfirmation" => "Cashback withdrawal confirmation",
"WAMSettingsNotificationsRecognitionBeingRecognised" => "Being recognised",
"WAMSettingsNotificationsRecognitionReachingMilestone" => "Reaching a milestone",
"WAMSettingsNotificationsRecognitionTop3" => "Coming top 3 in the leaderboard",
"WAMSettingsNotificationsPostTags" => "Tagged in a post",
"WAMSettingsNotificationsPostMentions" => "Mentioned in a comment",
"WAMSettingsNotificationPostComments" => "Comments on your posts",
"WAMSettingsNotificationGroupUserMoved" => "Moved group",

# -- Deactivated Users
"WAMDeactivatedUserMessage" => "Oops! This person cannot be found.\nThey may have left or have been removed by the admin.",

# -- Wallet Container
"WAMWalletContainerTitle" => "Wallet",
"WAMWalletContainerWithdrawTitle" => "Withdraw",
"WAMWalletContainerTransactionsTitle" => "Transactions",
"WAMWalletContainerRightButtonTitle" => "Help",

# -- Wallet Help
"WAMWalletHelpTitle" => "Wallet Help",
"WAMWalletHelpClose" => "Close",
"WAMWalletHelpFAQURL" => "https:#help.lifeworks.com/hc/en-gb/categories/201151013-Perks",

"WAMWalletHelpMyWalletTitle" => "What is My Wallet?",
"WAMWalletHelpMyWalletDetail" => "Your wallet is where all your cashback from online shopping is available to view and withdraw.",
"WAMWalletHelpTransactionsTitle" => "What is my transaction history?",
"WAMWalletHelpTransactionsDetail" => "Your transaction history displays all your purchases we've tracked and their state. Secure and easy to understand.",
"WAMWalletHelpMyCashbackTItle" => "How do I withdraw my Cashback?",
"WAMWalletHelpMyCashbackDetail" => "You can withdraw your cashback from your wallet to your bank account or PayPal account.",

"WAMWalletHelpFooterText" => "Need more information? Check out our ",
"WAMWalletHelpFooterButton" => "FAQ section",

# -- Wallet - Withdraw
"WAMWalletWithdrawAvailableTitle" => "Available to withdraw",
"WAMWalletWithdrawAvailableInfo" => "This is the value of funds available for you to withdraw now via your chosen method (bank account and PayPal).\n",
"WAMWalletWithdrawAvailableInfoDetail" => "You must have over %@ to withdraw funds.\n\n",
"WAMWalletWithdrawAvailableInfoFAQ" => "For more information visit our FAQ section.",

"WAMWalletWithdrawTrackedTitle" => "Cashback tracked",
"WAMWalletWithdrawTrackedInfo" => "This is the sum of funds that is being tracked by us and is in the process of being approved for you to withdraw soon.\n\nFor more information visit our FAQ section.",
"WAMWalletWithdrawWithdrawnTitle" => "Withdrawn to date",
"WAMWalletWithdrawWithdrawnInfo" => "This is the cumulative total amount of money that you have withdrawn from your LifeWorks wallet to date.\n\nFor more information visit our FAQ section.",

"WAMWalletMethodsExpandable" => "What's this?",

"WAMWalletBACSTitle" => "Bank Account",
"WAMWalletBACSInformation" => "You can withdraw your available cashback straight into your bank account. The withdrawal can take up to 14 days and you will be notified by email when it has been processed.",
"WAMWalletPaypalInformation" => "You can withdraw your available cashback from your wallet straight into your PayPal account. The withdrawal can take up to 14 days and you will be notified by email when it has been processed.",

"WAMWalletWithdrawHeaderDetail" => "You have saved %1$@ since you joined LifeWorks!",
"WAMWalletWithdrawMethodHeader" => "How would you like your money %@?",

"WAMWithdrawHeaderDetail" => "Amount to withdraw %@",
"WAMWithdrawHeaderAdditionalInfo" => "You will be charged %@ per withdrawal.",
"WAMWalletWithdrawExpandable" => "What's this?",
"WAMWalletWithdrawSaveDetails" => "Save my details",
"WAMWalletWithdrawSaveDetailsMore" => "Enabling this function will securely save your bank account details to make your future experience easier.",
"WAMWalletWithdrawAutomaticWithdraw" => "Automatic Withdraw",
"WAMWalletWithdrawAutomaticWithdrawMore" => "Turn on automatic withdraws to securely receive your money into your account when you have over %@ available.",

"WAMWalletWithdrawBACSInputNamePlaceholder" => "Name on Account (required)",
"WAMWalletWithdrawBACSInputSortcodePlaceholder" => "Sort Code (required)",
"WAMWalletWithdrawBACSInputNumberPlaceholder" => "Account Number (required)",

"WAMWalletWithdrawPaypalInputMailPlaceholder" => "Enter email address",

"WAMWalletCantWithdrawAlert" => "You need at least %@ available in your account to withdraw.",

# -- Wallet - Withdraw review
"WAMWalletWithdrawReviewTitle" => "Withdraw",
"WAMWalletWithdrawReviewInformationsTitle" => "Please check your details:",
"WAMWalletWithdrawReviewWithdrawButtonTitle" => "Withdraw",
"WAMWalletWithdrawReviewFooterTitle" => "Confirm your withdrawal:",
"WAMWalletWithdrawReviewPasswordTextFieldPlaceholder" => "Enter LifeWorks password",
"WAMWalletWithdrawReviewForgotPasswordButtonTitle" => "Forgot your password?",

"WAMWalletWithdrawReviewIncorrectPasswordTitle" => "Incorrect Password",
"WAMWalletWithdrawReviewIncorrectPasswordMessage" => "You have entered an incorrect password. Please try again.",

"WAMWalletWithdrawReviewBankAccountInformationsViewNameTitle" => "Name",
"WAMWalletWithdrawReviewBankAccountInformationsViewSortCodeTitle" => "Sort Code",
"WAMWalletWithdrawReviewBankAccountInformationsViewAccountNumberTitle" => "Account Number",

"WAMWalletWithdrawReviewPayPalInformationsViewEmailTitle" => "Email",

"WAMWalletWithdrawAlertTitle" => "Confirm Withdrawal",
"WAMWalletWithdrawAlertDesc" => "Enter your LifeWorks password to confirm your withdrawal",

# -- Wallet - Withdraw Confirmation
"WAMWalletWithdrawConfirmationTitle" => "Thank you",
"WAMWalletWithdrawConfirmationDetail" => "You'll recive an email confirming this transaction shortly.",
"WAMWalletWithdrawConfirmationInformation" => "You have withdrawn %@ to your %@. The payment is in progress and can take up to 14 days to process.",

# -- Wallet - Withdraw methods
"WAMWalletWithdrawMethodPayPal" => "PayPal",
"WAMWalletWithdrawMethodBankAccount" => "Bank Account",

# -- Wallet - Transactions
"WAMWalletTransactionsStateFooterTitle" => "For more information check out our",
"WAMWalletTransactionsStateFooterDescriptionTitle" => "FAQ section",

"WAMWalletTransactionsCashbackClaimRaisedStateTitle" => "Claim Raised",
"WAMWalletTransactionsCashbackClaimRaisedStateInformation" => "We're investigating your claim and will get back to you ASAP.",
"WAMWalletTransactionsCashbackConfirmedStateTitle" => "Confirmed",
"WAMWalletTransactionsCashbackConfirmedStateInformation" => "Your cashback has been confirmed by the retailer and is now in your wallet available to withdraw",
"WAMWalletTransactionsCashbackDeclineStateTitle" => "Final Decline",
"WAMWalletTransactionsCashbackDeclineStateInformation" => "We've investigated your cashback but unfortunatly it's been declined again. Refer to our FAQ section.",
"WAMWalletTransactionsCashbackTrackedQueriedStateTitle" => "Tracked: Queried",
"WAMWalletTransactionsCashbackTrackedQueriedStateInformation" => "We're investigating your query\nand will get back to you ASAP!",

"WAMWalletTransactionsWithdrawConfirmedStateTitle" => "Withdraw Confirmed",
"WAMWalletTransactionsWithdrawConfirmedStateInformation" => "Your withdrawal has been confirmed and will be avaiable in your chosen account shortly.",
"WAMWalletTransactionsWithdrawFailedStateTitle" => "Withdraw Failed",
"WAMWalletTransactionsWithdrawFailedStateInformation" => "Sorry, your withdrawal has failed on this occasion. Please check your withdraw details and try again.",
"WAMWalletTransactionsWithdrawRequestedStateTitle" => "Withdraw Requested",
"WAMWalletTransactionsWithdrawRequestedStateInformation" => "Your withdrawal has been requested and you should receive your cashback via your chosen payment method within 14 days.",

"WAMWalletTransactionsTrackedUnderDaysStateTitle" => "Tracked",
"WAMWalletTransactionsTrackedUnderDaysStateInformation" => "We've tracked your purchase and your Cashback is processing. We'll let you know when it’s available to withdraw.",
"WAMWalletTransactionsTrackedUnderDaysStateMoreInformation" => "If your cashback is still being tracked after 60 days you can query this with us and we will investigate it.",

"WAMWalletTransactionsTrackedOverDaysStateTitle" => "Tracked",
"WAMWalletTransactionsTrackedOverDaysStateInformation" => "Your cashback has been tracked for 60 days now and therefore you are entitle to make a query. We will respond to any queries as soon as possible.",
"WAMWalletTransactionsTrackedOverDaysStateTitleButtonTitle" => "Query",

"WAMWalletTransactionsQueryCashbackTitle" => "Query this Cashback",
"WAMWalletTransactionsQueryCashbackPlaceholder" => "Send us some information about your query. We will investigate the issue and get back to you ASAP.",

"WAMWalletTransactionsDeclinedTitle" => "Declined",
"WAMWalletTransactionsDeclinedInformation" => "Unfortunately your cashback has been declined. You can raise a claim and we will investigate the issue for you.",
"WAMWalletTransactionsDeclinedButtonTitle" => "Raise Claim",
"WAMWalletTransactionsQueryRaiseClaimTitle" => "RAISE A CLAIM",

"WAMWalletTransactionClaimRaisedTitle" => "Claim Raised",
"WAMWalletTransactionClaimRaisedInformation" => "We're investigating your claim\nand will get back to you ASAP.",

# -- Wallet empty view cards
"WAMWalletEmptyViewCard1WithdrawTitle" => "Your Wallet is empty",
"WAMWalletEmptyViewCard1WithdrawDescription" => "But not for long, don't worry!\nSwipe the screen and find all the\nways you can earn cashback.",
"WAMWalletEmptyViewCard1FooterTitle" => "Swipe the screen",
"WAMWalletEmptyViewCard2Title" => "Shop Online",
"WAMWalletEmptyViewCard2Description" => "Visit shop online! We have over\n1000 of the best retailers available!\nIt's time to give yourself a reward.",
"WAMWalletEmptyViewCard3Title" => "Restaurant Discounts",
"WAMWalletEmptyViewCard3Description" => "Bookatable we try\nto provide you all the possible\ncombinations to help you save\nmoney and have a great meal!",
"WAMWalletEmptyViewCard4Title" => "Local Deals",
"WAMWalletEmptyViewCard4Description" => "Getaways, goods, fun & events:\nneed a holiday, a new pair of\nheadphones or a skydive? Search\nour amazing offers!",
"WAMWalletEmptyViewCard1TransactionTitle" => "You have no transactions",
"WAMWalletEmptyViewCard1TransactionDescription" => "But not for long, don't worry!\nSwipe the screen and find all the\nways you can earn cashback.",

"WAMWalletTransactionTypeCashback" => "Cashback",
"WAMWalletTransactionTypeWithdraw" => "Withdraw",
"WAMWalletTransactionTypeCredit" => "Credit",

"WAMWalletTransactionStateConfirmed" => "Confirmed",
"WAMWalletTransactionStateTracked" => "Tracked",
"WAMWalletTransactionStateRequested" => "Requested",
"WAMWalletTransactionStateQuery" => "Tracked:Queried",
"WAMWalletTransactionStateDeclined" => "Declined",
"WAMWalletTransactionStateClaimed" => "Claim Raised",
"WAMWalletTransactionStateRejected" => "Rejected",
"WAMWalletTransactionStateFailed" => "Failed",

"WAMWalletTransactionMore" => "More Details",
"WAMWalletTransactionLess" => "Less Details",
"WAMWalletTransactionDetailDescription" => "Description",
"WAMWalletTransactionDetailStatus" => "Status",

"WAMWalletTransactionDetailPurchaseDate" => "Purchase Date",
"WAMWalletTransactionDetailPurchaseAmount" => "Purchase amount",
"WAMWalletTransactionDetailCashbackRate" => "Cashback rate",
"WAMWalletTransactionDetailCashbackEarned" => "Cashback earned",

"WAMWalletTransactionDetailWithdrawDate" => "Date",
"WAMWalletTransactionDetailWithdrawAmount" => "Withdraw amount",
"WAMWalletTransactionDetailPaypalEmail" => "PayPal email",
"WAMWalletTransactionDetailAccountName" => "Account name",
"WAMWalletTransactionDetailAccountSortCode" => "Sort Code",
"WAMWalletTransactionDetailAccountNumber" => "Account number",

"WAMWalletTransactionWithdrawPaypal" => "PayPal Withdraw",
"WAMWalletTransactionWithdrawBank" => "Bank Account",

"WAMWalletTransactionDetailCreditDate" => "Credit Date",

# Main menu button, only for accessibility
"WAMMenuLabel" => "Main menu",

# -- Left Menu */
"WAMMenuSectionWorkTitle" => "Work",
"WAMMenuSectionPerksTitle" => "Perks",
"WAMMenuSectionLifeTitle" => "Life",

"WAMMenuItemShopOnlineTitle" => "Shop Online",
"WAMMenuItemRestaurantDiscountsTitle" => "Restaurants",
"WAMMenuItemGiftCardsTitle" => "Gift Cards",
"WAMMenuItemLocalTitle" => "Local",
"WAMMenuItemInstoreOffersTitle" => "In-Store",
"WAMMenuItemColleagueOffersTitle" => "Exclusive Offers",
"WAMMenuItemWalletTitle" => "Wallet",
"WAMMenuItemColleagueDirectoryTitle" => "Colleague Directory",
"WAMMenuItemRecognitionFeedTitle" => "News Feed",
"WAMMenuItemLeaderboardTitle" => "Leaderboard",
"WAMMenuItemGiveNewRecognitionTitle" => "Give Recognition!",
"WAMMenuItemRewardsTitle" => "Rewards",
"WAMMenuItemEmployeeAssistanceTitle" => "Employee Assistance",
"WAMMenuItemCinemasTitle" => "Cinemas",

# -- Wellness
"WAMWBVCTitleAll" => "Wellbeing",

"WAMWBVCOnboardingCategoriesPrivacyText" => "Your company cannot see your choices.",
"WAMWBVCOnboardingCategoriesPleaseSelect" => "Choose some topics to personalise your daily wellbeing content",
"WAMWBVCOnboardingCategoriesNextButton" => "Next",
"WAMWBVCOnboardingCategoriesMaxAlert" => "You are only able to select up to %d items",
"WAMWBVCOnboardingCategoriesBackAlertTitle" => "If you cancel now, your topics selected will be discarded",

"WAMWBVCOnboardingSubcategoriesPleaseSelect" => "Select your relevant topics",
"WAMWBVCOnboardingSubcategoriesInstructions" => "You can select more than one topic and change them later if you decide.",

"WAMWBVCOnboardingSummaryStartButtonText" => "Start exploring",

"WAMWBVCOnboardingSummaryHeaderTitleText" => "Your wellbeing content",
"WAMWBVCOnboardingSummaryHeaderTitleSingleSelectionText" => "Your wellbeing content",
"WAMWBVCOnboardingSummaryHeaderQuestionText" => "What would you like to start with?",
"WAMWBVCOnboardingSummaryHeaderInstructionsText" => "Select your first topic",

"WAMWBVCSessionFinishReadingButton" => "Finish Reading",
"WAMWBArticleVCTitle" => "Daily Snack",

"WBUpsellTitle" => "Want More?",
"WBUpsellDismissButton" => "No Thanks",
"WBUpsellSkipButton" => "Skip",

"WBFeedbackTitle" => "Feedback",
"WBFeedbackDetail" => "Did you find this session helpful?",
"WBFeedbackBottomInfo" => "View all of the sessions you have participated in at any time in your profile",
# After participating in 'Leading With Fearless Control' by Eckhart Troll
"WBFeedbackTitleDescription" => "After participating in ‘%1$@’ by %2$@",
# Nothing to translate here
"WBFeedbackTitleDescriptionEnbolden" => "‘%1$@’",
"WAMWBNewsFeedOnboardingTitle" => "Improve your daily wellbeing",
"WAMWBNewsFeedOnboardingDescription" => "Use snackable wellbeing to make a happier and healthier you.",
"WAMWBNewsFeedOnboardingButton" => "Personalise your content",
"WAMWBNewsFeedPrivacy" => "Only you can see this",
"WAMWBNewsFeedViewActivityButton" => "View Activity",
"WAMWBNewsFeedSkipAnotherInterest" => "Set another topic",
"WAMWBNewsFeedSkipContinue" => "No, Continue",
"WAMWBNewsFeedSessionCompletionSkip" => "Next session",
"WAMWBNewsFeedSkipNewCategoryTitle" => "Would you like to select a new wellbeing topic?",
"WAMWBNewsFeedSkipAnotherCategoryTitle" => "Do you wish to focus on another one of your wellness interests?",
"WAMWBNewsFeedSkipSubtitle" => "You have skipped %d sessions",
"WAMWBNewsFeedSkipSubtitleToEnbolden" => " %d sessions",
"WAMWBNewsFeedSessionCompleteComeBackTomorrowHeaderTitle" => "Snacks completed, come back tomorrow for more!",
"WAMWBNewsFeedSessionCompleteCheckboxCellXOthers" => "%d Other snacks",
"WAMWBNewsFeedAdditionalInfo" => "Avoid use when driving or operating machinery. This track is not a substitute for therapy.",
"WAMWBNewsFeedContentStartReading" => "Start Reading",
"WAMWBNewsFeedContentStartListening" => "Start Listening",
"WAMWBNewsFeedContentContinueListening" => "Continue Listening",
"WAMWBNewsFeedContentAudioDuration" => "Duration: %@ mins",
"WAMWBNewsFeedContentStartWatching" => "Start Watching",
"WAMWBNewsFeedContentContinueWatching" => "Continue Watching",
"WAMWBNewsFeedContentAuthorDescription" => "By %1$@, %2$@",
"WAMWBNewsFeedContentMultipleAuthorsDescription" => "By %@",
"WAMWBNewsFeedYourDailyWellbeing" => "Your daily snack of wellbeing",
"WAMWBNewsFeedReEngagementSingleTopicTitle" => "Would you like to select a new wellbeing topic?",
"WAMWBNewsFeedReEngagementMultipleTopicsTitle" => "Do you wish to focus on another one of your wellbeing topics?",
"WAMWBNewsFeedReEngagementSkippedSubtitle" => "You have skipped %@",
"WAMWBNewsFeedReEngagementParticipatedSubtitle" => "You haven't participated for %@",

"WBReflectionTitle" => "Congratulations!",
"WBReflectionCompletedTitle" => "Well done! Snacks completed <br>on <b>%@</b>",
"WBReflectionCategoryCompletedTitle" => "Well done! You’ve completed all snacks <br>on <b>%@</b>",
"WBReflectionContinueTitle" => "Would you like to select a new topic?",
"WBReflectionContinueButtonTitle" => "Continue with %@",
"WBReflectionInterestsTitle" => "Or select",
"WBReflectionBottomTitle" => "Select new wellbeing topic",

"WBUpdateSessionProgressLabel" => "Updating your <b>Wellbeing</b> snacks!",
"WBUpdateActiveCategoryLabel" => "Updating your <b>Wellbeing</b> topic",

# -- Rate LifeWorks
"WAMRateLifeWorksAlertTitle" => "Rate this app!",
"WAMRateLifeWorksAlertMessage" => "If you enjoy using this app please take a second to rate it in the app store. Thanks for your support!",
"WAMRateLifeWorksAlertRateButton" => "Rate now",
"WAMRateLifeWorksAlertRemindButton" => "Remind me later",
"WAMRateLifeWorksAlertCancelButton" => "Don't ask again",

# -- WAMNotifications
"WAMNotificationViewControllerTitle" => "Notifications",
"WAMNotificationViewControllerEmptyViewTitle" => "No new notifications",
"WAMNotificationViewControllerEmptyViewContent" => "You will receive notifications when events occur in LifeWorks",

# -- Errors
"WAMErrorGenericText" => "Oops! It looks like something has gone wrong, please try again.",
"WAMErrorEmailConfirmationRequired" => "Email confirmation required.",

"WAMErrorCantFindContent" => "Oops! We can't find this content right now, please try again.",
"WAMErrorReRecogniseColleague" => "You've already re-recognised your colleagues!",
"WAMErrorImageValidation" => "Image should not exceed 2MB",

# -- WAMColleagueOffers
"WAMColleagueOffersEmptyScreenTitle" => "No offers available",
"WAMColleagueOffersEmptyScreenDescription" => "Come back soon to see some new offers!",
"WAMColleagueOffersDetailEmptyScreenTitle" => "Deal Unavailable",
"WAMColleagueOffersDetailEmptyScreenDescription" => "Oops this deal is no longer available.",
"WAMColleagueOffersSavedToClipboard" => "The code has been copied to your clipboard.",
"WAMColleagueOffersOpenWebsite" => "Visit Website",
"WAMColleagueOffersDetailsTaC" => "Offer Details and T&C's",
"WAMColleagueOffersClaimOnline" => "Claim Online",
"WAMColleagueOffersClaimInstore" => "Claim In-Store",
"WAMColleagueOffersTaCTitle" => "Offer Details and T&C's",
"WAMColleagueOffersTaCDetailsTitle" => "Offer Details",
"WAMColleagueOffersTaCTermsTitle" => "Terms and Conditions",
"WAMColleagueOffersClaimInstoreTitle" => "Claim In-Store",
"WAMColleagueOffersClaimInstoreSave" => "Save to Images",
"WAMColleagueOffersClaimOnlineTitle" => "Claim Online",
"WAMColleagueOffersValidUntil" => "Valid until %@",
"WAMColleagueOffersStartDate" => "Start date: %@",
"WAMColleagueOffersBarcodeSaved" => "Code has been saved to your camera roll.",
"WAMColleagueOffersPhotoError" => "To save a bar code, allow LifeWorks to access photos in your Settings app.",
"WAMColleagueOffersPhotoErrorTitle" => "Unable to save bar code",

# -- WAMDailyDeals
"WAMLocalTitle" => "Local",
"WAMDDCardViewFromSite" => "from %@",
"WAMDDCardViewCashback" => "%@ CASHBACK",
"WAMDDCardViewSavings" => "%@ CASHBACK | SAVE %@",
"WAMDDCardViewPreviousPrice" => "was %@",
"WAMDDRefineButton" => "Refine",
"WAMDDRefinedButton" => "Refined",
"WAMDDAllCategories" => "All categories",
"WAMDDFavouritesListTitle" => "Favourite Deals",
"WAMDDRefineFilterBy" => "Filter by",
"WAMDDRefineFilterRecommended" => "Recommended",
"WAMDDRefineFilterRecommendedNoInterests" => "Recommended (no interests)",
"WAMDDRefineNoInterestsAlertTitle" => "No interest selected",
"WAMDDRefineNoInterestsAlertText" => "Tell us what you're interested in and get personalised recommendations.",
"WAMDDRefineSortBy" => "Sort by",
"WAMDDRefineDealSites" => "Deal Sites",
"WAMDDRefinePriceRange" => "Price Range",
"WAMDDRefineSearch" => "Refine Search",
"WAMDDChangeLocationButtonGeneric" => "City",
"WAMDDChangeLocationButtonNearMe" => "Near me",

"WAMDDSharingEmailSubject" => "Check out this great offer from LifeWorks!",
"WAMDDSharingEmailContent" => "Check out this offer from LifeWorks:\n\n%@\n%@\nGet this offer now by using this link in your browser: %@",
"WAMDDFavouriteRemoveTitle" => "Remove this item from favourites?",
"WAMDDFavouriteRemoveButton" => "Remove",

# -- WAMDDDetails
"WAMDDDetailsTitle" => "The Deal",
"WAMDDDetailsDescription" => "Description",
"WAMDDDetailMoreCashbackFooterTitle" => "Your Cashback can take up to 7 working days to be tracked, and typically up to 90 days to be confirmed.",
"WAMDDDetailGetDealButtonTitle" => "Get This Deal",
"WAMDDDetailGetDealButtonTitleExpired" => "This Deal Has Expired",
"WAMDDDetailGetDirections" => "Get Directions",

# -- WAMDDRefine
"WAMDDRefineFormatPriceFrom" => "from: %@",
"WAMDDRefineFormatPriceTo" => "to: %@",
"WAMDDRefineEndingSoon" => "Ending Soon",
"WAMDDBiggestDiscount" => "Biggest Discount",
"WAMDDPriceLowToHigh" => "Price Low to High",
"WAMDDPriceHighToLow" => "Price High to Low",
"WAMDDPopularity" => "Popular in your Network",

# -- WAMDDSearch
"WAMDDSearchRecentSearch" => "Recent Searches",
"WAMDDSearchPlaceholder" => "Search retailers or products",
"WAWLocalSearch" => "\"%@\" in Local",

# -- WAMDDLocation
"WAMDDLocationSearchPlaceholder" => "Search for a City",

# -- WAMDDNoResult
"WAMDDNoResultTitle" => "Oops, no results!",
"WAMDDNoResultDescription" => "We couldn't find any matching results, please try again.",

# -- WAMGiftCards
"WAMGCMenuTitle" => "Gift Cards",
"WAMGCDeliveryEmailTitle" => "Enter the email address you would like your gift card to be sent to",

"WAMGCBrowseByCategory" => "Browse by Category",
"WAMGCCategoryAll" => "All",
"WAMGCPopularGiftCards" => "Popular Gift Cards",

# -- WAMGiftCardsCardView
"WAMGiftCardsCardViewTitle" => "Buy gift cards for up to %@ off.",
"WAMGiftCardsCardViewDescription" => "Save on everyday purchases with discount gift cards to your favourite stores",

# -- WAMGiftCardsList
"WAMGiftCardsDiscountKey" => "%@ Discount",
"WAMGiftCardDigitalTypeKey" => "Digital Card",

# -- WAMGiftCardsDetail
"WAMGiftCardsDetailTitle" => "Gift Card Detail",

"WAMGiftCardsDetailDeliveryInformation" => "Delivery Information",
"WAMGiftCardsDetailDeliveryTextDigital" => "Once you purchase this gift card you will be sent an email with a link on it. Once you click on the link you will be able to redeem your gift card.",
"WAMGiftCardsLifeWorksTerms" => "LifeWorks Terms and Conditions",
"WAMGiftCardsRetailerTerms" => "Retailer Terms and Conditions",

"WAMGiftCardsDetailBuyPriceRange" => "Amount between %@ - %@",
"WAMGiftCardsDetailBuyYouPay" => "You pay",
"WAMGiftCardsDetailBuyNow" => "Buy Now",
"WAMGiftCardsDetailBuySelectAmount" => "Select an Amount",
"WAMGiftCardsDetailBuyErrorGeneric" => "Sorry, something didn't work.",
"WAMGiftCardsDetailBuyErrorPriceRangeMin" => "Minimum amount is %@",
"WAMGiftCardsDetailBuyErrorPriceRangeMax" => "Maximum amount is %@",
"WAMGiftCardsDetailBuyLoading" => "Loading...",

"WAMGiftCardsDetailTermsAndConditions" => "Terms and Conditions",
"WAMGiftCardsDetailAboutTheBrand" => "About the Brand",

"WAMGCConfirmationEmailViewTitle" => "Great %@! Your Order has been placed successfuly. Your gift cards will be sent to:",

# -- WAMGiftCardsTermsAndConditions
"WAMGiftCardsLifeWorksTermsAndConditions" => "Offers and discount rates are correct at the time of publishing.\nAll discounts are on the value of the Gift Card and are applied at the point of Gift Card purchase.\nGift Card purchases and fulfilment are handled by a 3rd party.\nThis Gift Card is redeemable In-Store.\nAny Gift Card enquiries should be directed at LifeWorks Support.\nFor more information about all Gift Cards please refer to our Help & FAQs pages.\nIn the event that the Gift Card is not delivered or does not work, you should see our Help and FAQs pages.\nFor more information about this Gift Card, please see the retailer terms below.",

"WAMGiftCardsLifeWorksTermsAndConditionsDigital" => "Offers and discount rates are correct at the time of publishing.\nAll discounts are on the value of the Gift Card and are applied at the point of Gift Card purchase.\nGift Card purchases and fulfilment are handled by a 3rd party.\nThis Gift Card is redeemable online.\nAny Gift Card enquiries should be directed at LifeWorks Support.\nFor more information about all Gift Cards please refer to our Help & FAQs pages.\nIn the event that the Gift Card is not delivered or does not work, you should see our Help and FAQs pages.\nFor more information about this Gift Card, please see the retailer terms below.",

"WAGCHowtoRedeem" => "You will receive a confirmation email soon. Please click on the link within the email and you will be able to redeem your gift card.",

# -- WAMGiftCardsAskQuestion
"WAMGCAskQuestionTitle" => "Need help with Gift Cards?",
"WAMGCAskQuestionButtonText" => "Ask us a question",

"WAMGCAskQuestionGenericSubject" => "Question about Gift Cards",
"WAMGCAskQuestionGenericBodyHeader" => "Dear LifeWorks Support,\n",
"WAMGCAskQuestionGenericBodyFooter" => "Thank you,\n%@",

"WAMGCAskQuestionRetailerSubject" => "Question about the %@ Gift Card",
"WAMGCAskQuestionRetailerBodyHeader" => "Dear LifeWorks Support,\n",
"WAMGCAskQuestionRetailerBodyFooter" => "Thank you,\n%@",

# -- WAMGiftCardSearch
"WAMGiftCardSearchHint" => "Search for \"%@\"",
"WAMGCSearchPlaceholder" => "Search for Gift Cards",

# -- Restaurant 2.0
"WAMRSRefineTitle" => "Refine",
"WAMRSRefineButton" => "Refine",
"WAMRSRefinedButton" => "Refined",
"WAMRSChangeLocationButtonGeneric" => "Location",
"WAMRSChangeLocationButtonNearMe" => "Near me",
"WAMRSFavouriteRestaurants" => "Favourite Restaurants",
"WAMRSNoDirections" => "Directions unavailable for this restaurant",
"WAMRSSearchQuery" => "Search for \"%@\"",
"WAMRSSearchResultTitle" => "%1$@ near %2$@",
"WAMRSSearchResultNearMeTitle" => "%@ near me",

"WAMRSListEmptyScreenTitle" => "Oops, no restaurants in this location",
"WAMRSListEmptyScreenDescription" => "Try changing your search area in the bar below.",

"WAMRSListEmptySearchScreenTitle" => "Oops, no results!",
"WAMRSListEmptySearchListScreenDescription" => "No results for \"%1$@\" %2$@. Try searching for something else or changing your search area.",
"WAMRSListEmptySearchMapsScreenDescription" => "No results for \"%1$@\" %2$@. Try searching for something more general or expanding your search area.",
"WAMRSListEmptySearchListScreenLocation" => "in your location",
"WAMRSListEmptySearchMapsScreenLocation" => "in this selected area",

"WAMRSSearchRecentSearch" => "Recent Searches",
"WAMRSSearchPlaceholder" => "Search restaurants",
"WAMRSMapSelectedArea" => "Selected Area",
"WAMRSSearchAreaButton" => "Search this area",

"WAMRSDetailMainButtonPopup" => "Book a Table",
"WAMRSDetailMainButtonCall" => "Call Restaurant",
"WAMRSDetailMainButtonVoucherCode" => "Show Code",
"WAMRSDetailMainButtonMembershipCard" => "Show Card",
"WAMRSDetailMainButtonMembershipCardAndRedeem" => "Show Card & Redeem",

"WAMRSDetailTitle" => "Details",
"WAMRSDetailOverview" => "Overview",
"WAMRSDetailWebsite" => "View Website",
"WAMRSDetailOpeningTimes" => "Opening Times",
"WAMRSDetailAveragePrice" => "Average Cost",
"WAMRSDetailAveragePriceOneMainCourse" => "One Main Course",
"WAMRSDetailAveragePriceThreeMainCourse" => "Three Course Meal",
"WAMRSDetailAdditionalInfo" => "Additional Info",
"WAMRSDetailSpecialOffers" => "Special Offers",
"WAMRSDetailTerms" => "Terms & Conditions",
"WAMRSDetailSeeAll" => "See All",
"WAMRestaurantDetailHowToClaimTitle" => "How to Claim",
"WAMRestaurantDetailHowToClaimDetail" => "1. This restaurant requires a phone booking, please mention your Hi-Life card\n2. Present your card when requesting the bill to claim your discount",

"WAMRSApiErrorTitle" => "Oops, something went wrong!",
"WAMRSApiErrorDesc" => "Please try again later.",
"WAMRSCardMemberNo" => "Member no: %@",
"WAMRSCardMembershipExpire" => "Membership expires %@",
"WAMRSCardUsedOn" => "Card used on: %@",

"WAMRSChangeLocationSearchPlaceholder" => "City, location, postcode",

"WAMPhoneInteractorInvalidPhoneNumber" => "Invalid phone number.",
"WAMPhoneInteractorDeviceCannotMakeCallsNow" => "No SIM card installed.",
"WAMPhoneInteractorDeviceNotCapable" => "This iOS Device is not capable of making calls.",

"WAMRSFavouriteRemoveTitle" => "Remove this item from favourites?",
"WAMRSFavouriteRemoveButton" => "Remove",

"WAMRSCashbackPerPerson" => "Cashback per person",
"WAMRSBookThisOffer" => "Book This Offer",

"WAMRSConfirmationBATitle" => "You have not yet confirmed your booking. Are you sure you want to exit?",
"WAMRSConfirmationBATYes" => "Yes",
"WAMRSConfirmationBATNo" => "No",

"WAMRSNoFavouritesTitle" => "No favourites",

"WAMRSRefineOptionAll" => "All Cuisines",

"WAMRSRefineAllCuisines" => "All Cuisines",

"WAMRSRedeemCodeTerms" => "For more information see T&Cs",
"WAMRSRedeemCodeTermsLink" => "T&Cs",
"WAMRSRedeemCodeDetail" => "Show this code to redeem your offer",
"WAMRSRedeemCodeRestaurantNameAndCode" => "%@ Code",

# WAMNetworkErrorView
"WAMNetworkErrorViewTryAgain" => "Try again",
"WAMNetworkErrorViewNoInternetConnectionTitle" => "No Internet Connection!",
"WAMNetworkErrorViewNoInternetConnectionDetail" => "We're having trouble connecting\nto the server, please check your\nconnection and try again",

# -- Life
"WAMEmployeeAsstanceTitleLabel" => "Employee Assistance",
"WAMCounselorSearchTitleLabel" => "Counsellor Search",

# Package Info Lite
"WAMPackageInfoLiteTitle" => "LifeWorks Lite",
"WAMPackageInfoLiteSubtitle" => "Your Company's LifeWorks Premium has expired.",
"WAMPackageInfoLiteDetailOne" => "Don't worry, it still works. However, until your company upgrades, you will receive LifeWorks Lite only:",
"WAMPackageInfoLiteDetailTwo"=>"\n• Basic Social Features\n\n• Lower Discounts & Cashbacks\n\n• Limited Restaurants discounts\n\n• Wallet withdrawal fees",
"WAMPackageInfoLiteSubdetail"=>"To upgrade to LifeWorks Premium, contact your network administrator.",
"WAMPackageInfoLiteMainActionButtonTitle" => "Got it",
"WAMPackageInfoLiteBottomBarTitle"=>"To learn more about our features visit our website",

# Package Info Premium
"WAMPackageInfoPremiumTitle" => "LifeWorks Premium",
"WAMPackageInfoPremiumSubtitle" => "Your company has upgraded to LifeWorks Premium",
"WAMPackageInfoPremiumDetailOne" => "Congratulations, your company has upgraded to LifeWorks Premium! Here's a snapshot of some the benefits you get with LifeWorks Premium:",
"WAMPackageInfoPremiumDetailTwo"=>"\n• Enhanced Social Features\n\n• Boosted and Exclusive Discounts & Cashbacks\n\n• Unlimited Retailers and Restaurants discounts",
"WAMPackageInfoPremiumSubdetail"=>"",
"WAMPackageInfoPremiumMainActionButtonTitle" => "Got it",
"WAMPackageInfoPremiumBottomBarTitle"=>"To learn more about our features visit our website.",

# -- Rewards Walkthrough
"WAMRWHelpNavigationBarTitle" => "Rewards Help",
"WAMRWHelpViewTitle1" => "Get Rewarded",
"WAMRWHelpViewTitle2" => "Choose your Reward",
"WAMRWHelpViewTitle3" => "Enjoy!",
"WAMRWHelpViewSubTitle1" => "You will receive a notification to let you know that you've been rewarded.",
"WAMRWHelpViewSubTitle2" => "You will then be able to choose from a wide variety of Rewards. So sit back and enjoy!",
"WAMRWHelpViewSubTitle3" => "Once you've chosen your Reward, we'll take care of everything else.",
"WAMRWHelpViewButtonTitle2" => "Got it!",

# -- Cinemas
"WAMCILandingBottomButtonTitle" => "How does it work?",
"WAMCIHeaderCardViewTitle" => "How does it work?",
"WAMCIHeaderCardViewDescription" => "Buy discount codes from the cinema providers listed below and redeem at the cinema or online",
"WAMCIHeaderBannerViewTitle" => "Cinema Tickets at Great Prices",
"WAMCIHeaderBannerViewSubtitle" => "Up to %@ discount nationwide",
"WAMCIOutOfStockLabelTitle" => "OUT OF STOCK",

"WAMCITermsAndConditionsTitle" => "Terms and Conditions",
"WAMCILocationTitle" => "Choose your cinema location",
"WAMCILocationPickerTitle" => "Please select",
"WAMCILocationError" => "Please choose a cinema",
"WAMCIBuyButtonTitle" => "Buy Now",
"WAMCIPriceSubtitle" => "Including VAT",
"WAMCIAboutTitle" => "About This Offer",
"WAMCIHowToRedeemTitle" => "How to redeem?",
"WAMCIThingsToKnowTitle" => "Important things to know",
"WAMCIAvaibleInOtherCinemasTitle" => "Valid at the following %@ cinemas",
"WAMCIOfferPrice" => "Price: %@",
"WAMCIMerchantDescription" => "Save up to 40% on cinema tickets",
"WAMCIConfirmationEmailViewTitle" => "Great %@! Your Order has been placed successfuly. A confirmation email has been sent to:",

# -- Payment
"WAMPaymentEnterCardInformation" => "Enter your payment information",
"WAMPaymentSaveCardDetails" => "Save Card Details",
"WAMPaymentNumberTitle" => "Credit Card",
"WAMPaymentNumberPlaceholder" => "Card Number",
"WAMPaymentNumberError" => "The card number is not a valid credit card number.",
"WAMPaymentExpiryDateTitle" => "Expiry Date",
"WAMPaymentExpiryMonthPlaceholder" => "MM",
"WAMPaymentExpiryMonthError" => "The card’s expiration month is invalid.",
"WAMPaymentExpiryYearPlaceholder" => "YY",
"WAMPaymentExpiryYearError" => "The card’s expiration year is invalid.",
"WAMPaymentSecurityTitle" => "Security Code",
"WAMPaymentSecurityPlaceholder" => "CVC",
"WAMPaymentSecurityError" => "The card’s security code is incorrect.",
"WAMPaymentPayButton" => "Pay %@",

"WAMPaymentErrorTitle" => "Payment failed",
"WAMPaymentApplePayUnavailable" => "Apple Pay is unavailable, you can pay with credit card instead.",
"WAMPaymentAPIError" => "Sorry, it looks like there was a problem when processing your order. We apologise for the inconvenience. Please try again with a different card.",
"WAMPaymentGatewayError" => "Sorry, it looks like there was a problem when processing your payment. We apologise for the inconvenience. Please try again with a different card.",

# - Payment Errors
"WAMPaymentOutOfStockError" => "Sorry, it looks like this product is currently out of stock. We apologise for the inconvenience.",
"WAMPaymentChargeAuthorizationFailureError" => "There has been a problem taking payment from your card, please try again. If this problem persists please try with a different card or contact customer support and quote ref:20101",
"WAMPaymentChargeCaptureFailureError" => "There has been a problem taking payment from your card, please try again. If this problem persists please try with a different card or contact customer support and quote ref:20102",
"WAMPaymentChargeRefundFailureError" => "We have taken the purchase amount from your card to check its validity and have not been able to refund it back to your card. Please contact customer support to find out more quoting ref:20103 and sorry for the inconvenience",
"WAMPaymentSaveCardFailureError" => "We have been unable to save your card, please try again. If this problem persists please contact customer support and quote ref:20150",
"WAMPaymentDiscountResolverError" => "We have not been able to apply the right discount to your purchase. Please contact customer support for more information and quote ref:20010",
"WAMPaymentConfirmationEmailNotSentError" => "We have been unable to send your confirmation email to you, please get in touch with customer support quoting ref:20020 and they will be able to resend your email",
"WAMPaymentChargeGeneralError" => "There has been an error with your payment, please try again. If this problem persists please try with a different card or contact customer support and quote ref:20100",
"WAMPaymentNGCAPIError" => "We are having a problem with this product, please try again later. If this problem persists please contact customer support and quote ref:20500",

# -- LifeworksMigrationPopUp
"WAMLifeWorksMigrationPopupTitle" => "Welcome to the new look LifeWorks!",
"WAMLifeWorksMigrationPopupText" => "It’s the same great content you know and trust, with a brand new look and feel. We've added some great features plus a new app so you can access LifeWorks from your mobile device.\n\nWe hope you love it as much as we do",
"WAMLifeWorksMigrationPopupButtonTitle" => "Continue to LifeWorks",

# -- WAMSharesToGroupView
"WAMShareToGroupViewLabelTitle" => "Share to: %@",

# -- WAMGroupSelectionTableViewController
"WAMGroupSelectionTableViewControllerTitle" => "Select Group",

# -- WAMCheckout
"WAMCheckoutTitle" => "Checkout",
"WAMDeliveryEmailPlaceholder" => "Email Address",
"WAMDeliveryEmailError" => "Please enter a valid email address.",
"WAMCheckoutCardButton" => "Pay with Card",
"WAMCheckoutTotal" => "Total: %1$@ %2$@",
"WAMCheckoutEmptyEmailError" => "Enter your email.",
"WAMCheckoutHeaderTitle" => "%1$@ (%2$@)", # Cinema name(Cinema location) etc: Odeon(Surrey)
"WAMCheckoutCancelAlertTitle" => "Exit Payment Process",
"WAMCheckoutCancelAlertMsg" => "If you cancel, all your payment progress will be lost.",
"WAMCheckoutPaymentSuccessfulTitle" => "Payment Successful",
"WAMSavedCardTitle" => "Pay with your saved card",
"WAMSavedCardFooter" => "*To pay with another card click ‘Remove’ and enter the card details on the following page. This action will unsave the current card information.",
"WAMSavedCardRemove" => "Remove",
"WAMConfirmationOrderViewTitle" => "Your order ID is: %@",
"WAMConfirmationEmailViewSubtitle" => "Order ID: %@. Remember to make a note of this for your future reference. ",
"WAMConfirmationNoteViewTitle" => "Note",
"WAMConfirmationNoteViewText" => "If you have any enquiries about this order, please do not hesitate to <a href=>\"mailto:support@lifeworks.com\">contact our customer support.</a>",
"WAMConfirmationNoteEmailSubject" => "Questions about Cinemas",
"WAMConfirmationNoteEmailBody" => "Dear LifeWorks,\n\n\n\n Thank you, %@",
"WAMCheckoutPurchasedItems" => "%1$ld x %2$@", # amount x item title etc: 2xAdult Tikets

# -- Update app screen
"WAMAppUpdateGenericTitle" => "Get the most out of LifeWorks by installing the latest update",
"WAMAppUpdateGenericSubtitle" => "We release regular updates to the app to ensure that you have best experience.",
# -- Update app screen */
"WAMUpdateButtonTitle" => "Update app",
}